---
- name: Install Ilias for Export Projects
  hosts: ilias
  gather_facts: true


  roles:
    - 01-common_server
    - 02-mysql
    - 03-apache
    - 04-ilias
    - 05-lucene
    - 06-plugins
    - 07-le


  vars_files:
    - vaulted_vars.yml
    - vars.yml
