filetype on          " Détection du type de fichier 
syntax on            " Coloration syntaxique
set background=dark  " Adapte les couleurs pour un fond noir (idéeal dans PuTTY)
set linebreak        " Coupe les lignes au dernier mot et pas au caractère (requier Wrap lines, actif par défaut)
set showmatch        " Surligne le mots recherchés dans le texte
set hlsearch         " Surligne tous les résultats de la recherche
set autoindent       " Auto-indentation des nouvelles lignes
set expandtab        " Remplace les Tabulation par des espaces
set shiftwidth=2     " (auto) Indentation de 2 espaces
set smartindent      " Active smart-indent (améliore l'auto-indentation, notamment en collant du texte déjà indenté)
set smarttab         " Active smart-tabs (améliore l'auto-indentation, Gestion des espaces en début de ligne pour l'auto-indentation)
set softtabstop=2    " Tabulation = 2 espaces
set backup           " Fait une copie de sauvegarde lors de l'écrasement d'un fichier
set backupdir=~/.cache/vim/backup   " Dossier contenant la sauvegarde.
set shell=/bin/zsh   " Shell par défaut
set mouse=           " Pas de souris
set clipboard=autoselect    " Le texte sélectionné en mode visuel est collé dans le presse-papier CLIPBOARD
set showmatch        " Paranthèse electrique
set wrapscan         " La recherche reprend au début du fichier (resp à la fin) une fois la fin atteint
set history=2000     " Taille de l'historique de la barre de commandes
set ruler            " Affichage de la position dans le fichier dans la barre de statut
set undolevels=150   " Nb undo, pour revenir en arrière
set encoding=utf-8   " Encoding
colo desert 

' Conf Ansible
autocmd FileType yml,yaml setlocal ts=2 sts=2 sw=2 expandtab et ai cuc colorscheme torte