---
- name: relancer Apache
  systemd:
    name: httpd
    state: restarted

- name: restart php-fpm
  systemd:
    name: php-fpm
    state: restarted

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: reload firewalld
  systemd:
    name: firewalld
    state: reloaded