---
- name: relancer Apache
  systemd:
    name: httpd
    state: restarted

- name: reload firewalld
  systemd:
    name: firewalld
    state: reloaded

- name: reload systemd
  systemd:
    daemon_reload: yes