---
- name: Activer le module stream de PHP
  dnf:
    name: '@php:8.0'
    state: present

- name: Installation des paquets pour Apache
  dnf:
    name:
      - httpd
      - httpd-manual
      - httpd-tools
      - mod_xsendfile
      - memcached
      - mod_ssl
    state: latest
    disable_gpg_check: yes

- name: Installation des paquets PHP
  dnf:
    name:
      - php
      - php-cli
      - php-common
      - php-fpm
      - php-gd
      - php-intl
      - php-json
      - php-mbstring
      - php-mysqlnd
      - php-opcache
      - php-pdo
      - php-xml
      - php-pecl-zip
      - php-soap
    state: latest

- name: Configuration des modules Apache
  copy:
    dest: /etc/httpd/conf.modules.d/99-custom-modules.conf
    content: |
      # Modules chargés par Ansible
      LoadModule ssl_module modules/mod_ssl.so
      LoadModule headers_module modules/mod_headers.so
      LoadModule speling_module modules/mod_speling.so
      LoadModule rewrite_module modules/mod_rewrite.so
      LoadModule xsendfile_module modules/mod_xsendfile.so
    owner: root
    group: root
    mode: '0644'
  notify: relancer Apache

- name: Sécurisation d'Apache - paramètres globaux
  copy:
    dest: /etc/httpd/conf.d/00-security.conf
    content: |
      # Configuration de sécurité Apache - Géré par Ansible
      ServerSignature Off
      ServerTokens Prod
      Timeout 40
      ServerLimit 60
    owner: root
    group: root
    mode: '0644'
  notify: relancer Apache

- name: Configuration du répertoire LMS spécifique
  blockinfile:
    path: /etc/httpd/conf.d/lms_directory.conf
    create: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK - LMS DIRECTORY"
    block: |
      <Directory "{{ ilias_dir }}">
        AllowOverride All
        Options FollowSymLinks
        Require all granted
      </Directory>
  notify: relancer Apache

- name: On securise PHP
  lineinfile:
    dest: /etc/php.ini
    regexp: '^expose_php\s*='
    line: "expose_php = Off"
  notify: relancer Apache

- name: Désactivation du virtualhost par défaut (welcome.conf)
  copy:
    dest: /etc/httpd/conf.d/welcome.conf
    content: |
      # Désactivé par Ansible - Remplacé par configuration ILIAS
      # Le contenu original a été commenté pour éviter les conflits
      #
      # <LocationMatch "^/+$">
      #    Options -Indexes
      #    ErrorDocument 403 /.noindex.html
      # </LocationMatch>
      #
      # <Directory /usr/share/httpd/noindex>
      #    AllowOverride None
      #    Require all granted
      # </Directory>
    owner: root
    group: root
    mode: '0644'
  notify: relancer Apache

- name: Création du répertoire pour override systemd
  file:
    path: /etc/systemd/system/httpd.service.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Optimisation d'Apache - limites de fichiers
  copy:
    dest: /etc/systemd/system/httpd.service.d/limits.conf
    content: |
      [Service]
      LimitNOFILE=128000
    owner: root
    group: root
    mode: '0644'
  notify:
    - reload systemd
    - relancer Apache

- name: Activation du service Apache
  systemd:
    name: httpd
    state: started
    enabled: yes

- name: Configuration du pare-feu pour les services HTTP et HTTPS
  firewalld:
    service: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  loop:
    - http
    - https
  notify: reload firewalld

- name: Vérification que les services HTTP et HTTPS sont bien activés dans le pare-feu
  command: firewall-cmd --list-services
  register: firewall_services
  changed_when: false
  check_mode: no

- name: Affichage des services activés dans le pare-feu
  debug:
    msg: "Services activés dans le pare-feu : {{ firewall_services.stdout }}"
  when: firewall_services.stdout is defined