# installation et configuration de letsencrypt pour AlmaLinux 8
- name: Installation de certbot
  dnf:
    name: 
      - certbot
      - python3-certbot
    state: present
  tags: le

- name: Arrêt du service Apache
  systemd:
    name: httpd
    state: stopped
  tags: le
  ignore_errors: yes
  
- name: Création du certificat avec standalone
  command: "certbot certonly --standalone -d {{ server_name }} -m {{ certbot_mail_address }} --agree-tos --noninteractive"
  tags: le
  args:
    creates: /etc/letsencrypt/live/{{ server_name }}/cert.pem

- name: Ajout des hooks pour le renouvellement
  lineinfile:
    path: /etc/letsencrypt/renewal/{{ server_name }}.conf
    line: "{{ item }}"
    insertafter: EOF
  with_items:
    - "post_hook = systemctl start httpd"
    - "pre_hook = systemctl stop httpd"
  tags: le

- name: Commenter la ligne Listen 443 dans le fichier ssl.conf
  replace:
    path: /etc/httpd/conf.d/ssl.conf
    regexp: '^Listen 443 https'
    replace: '# Listen 443 https'
  notify: relancer Apache
  tags: le

- name: Configuration de la redirection SSL
  blockinfile:
    dest: /etc/httpd/conf.d/lms.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK - SSL REDIRECT"
    block: |
      <VirtualHost *:80>
        ServerName {{ server_name }}
        Redirect permanent / https://{{ server_name }}/
      </VirtualHost>
  notify: relancer Apache

- name: Création du virtualhost SSL
  template:
    src: templates/{{ virtualhost_name }}.j2
    dest: /etc/httpd/conf.d/{{ virtualhost_name }}
    owner: root
    group: root
    mode: '0644'
  notify: relancer Apache

- name: Activation du module SSL pour Apache
  copy:
    dest: /etc/httpd/conf.modules.d/00-ssl.conf
    content: |
      LoadModule ssl_module modules/mod_ssl.so
      Listen 443 https
      SSLPassPhraseDialog exec:/usr/libexec/httpd-ssl-pass-dialog
      SSLSessionCache         shmcb:/run/httpd/sslcache(512000)
      SSLSessionCacheTimeout  300
      SSLCryptoDevice builtin
    owner: root
    group: root
    mode: '0644'
  notify: relancer Apache

- name: Démarrage du service Apache
  systemd:
    name: httpd
    state: started
    enabled: yes
  tags: le