---
- name: Installer ssmtp
  yum:
    name: ssmtp
    state: present

- name: Configurer ssmtp
  template:
    src: ssmtp.conf.j2
    dest: /etc/ssmtp/ssmtp.conf
    owner: root
    group: root
    mode: '0644'

- name: Assurer que ssmtp utilise sendmail
  alternatives:
    name: mta
    path: /usr/sbin/ssmtp
